spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 379936347987-8n3924r6qgomk4f8o9u97nm3amom6a0c.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: aN_Wa9A3zU_3Iqsi9AT8
            client-secret: 5aVyWnQDF6
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: 7e9b2d44833ae97e8ee2270aced57a4d
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id